image: cyberjacob/android-sonarqube-docker

variables:
  ANDROID_COMPILE_SDK: "25"
  ANDROID_BUILD_TOOLS: "25.0.2"
  ANDROID_SDK_TOOLS: "25.3.1"
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  - test
  - release
  - publish

build_test:
  stage: build
  script:
    - GRADLE_OPTS="-Xlint:deprecation -Xlint:unchecked -Xlint:deprecation"
    - ./gradlew --no-daemon -g /cache :app:assembleDebug
  artifacts:
    untracked: true
    expire_in: 5 mins

unitTests:
  stage: test
  script:
    - ./gradlew --no-daemon -g /cache :app:test

#functionalTests:
#  image: gitlab.itvet.co.uk:4567/jacob.mansfield/android-sonarqube-docker:SDK_TOOLS-${ANDROID_SDK_TOOLS}-SDK-${ANDROID_COMPILE_SDK}-BUILD_TOOLS-${ANDROID_BUILD_TOOLS}
#  stage: test
#  script:
#    - wget --quiet --output-document=android-wait-for-emulator https://raw.githubusercontent.com/travis-ci/travis-cookbooks/0f497eb71291b52a703143c5cd63a217c8766dc9/community-cookbooks/android-sdk/files/default/android-wait-for-emulator
#    - chmod +x android-wait-for-emulator
#    - echo y | android --silent update sdk --no-ui --all --filter sys-img-x86-google_apis-${ANDROID_COMPILE_SDK}
#    - echo no | android create avd -n test -t android-${ANDROID_COMPILE_SDK} --abi google_apis/x86
#    - emulator64-x86 -avd test -no-window -no-audio &
#    - ./android-wait-for-emulator
#    - adb shell input keyevent 82
#    - ./gradlew --no-daemon cAT

SonarQube:
  stage: test
  script:
    - ./gradlew --no-daemon -g /cache sonarqube -Dsonar.host.url=https://sonarqube.itvet.co.uk -Dsonar.login=4dd893d5d11943c207a420bf31ac4ac4c4428798

release:
  stage: release
  script:
    - ./gradlew --no-daemon -g /cache :app:assembleRelease
  artifacts:
    paths:
    - app/build/outputs/apk/*.apk
  dependencies: []
